# Bun configuration for bun-ioc module

[install]
# Configure package installation behavior
auto = "auto"
peer = true

[test]
# Test configuration
# Preload reflect-metadata so decorator metadata is available in tests
preload = ["reflect-metadata"]

[run]
# Runtime configuration
# Use a valid shell option for Bun
shell = "system"
